language: python
python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- nightly
install:
- pip install .
script:
- py.test tests
deploy:
  provider: pypi
  user: kalekundert
  password:
    secure: BY1Uvdzrmo/ydw0svBEPIwyYV7PojE+BhMxT4vdk9MbOK1t57T83eRO01WYnIM1AoRGVutto5PgiOuE+IptBTVClMfBhH0JwN7crZ6reNdWWwV0NH0FzFunhYGwZ8aLnv8g8qYJ1wABxVFjOudpfnrAQ1tQczEmGwr9WGwd63PIOnpcP88xmkP8cRDqbP1FrgK6nAmvSHVcqKXstjFizydJ8v4R97Ix8+cynrDNmWqFX6T1yoDM8wXW3BePP3X/Ag64TmANEfsN83H+oE8GAsd62IbfT5FJZR7lidGi4qKVMOmGLOZPJGdxLk0kv/3MYOnXWUS530bBPt/KlbxnjSSEaHGyHO2ZPA7LBt8W21sZkA5/haElk0E4bZ4+PqLvMRdNvDqJka0jm3vnqM1d760GsxCU/I0wPJObnVrwiwWeHftJv7KT644B0fJgJpXJ8aymqmAenxjBIcmc6TCFmSfF2jyI0zAUUc+w1Hc/uPItViJr4GTjJqxbKOvoubktGi3KEAEUtwoBkwZ6Pr03nTxg2SDDBeGyU5ne4GEJWLug3cKFAdJNNyu6E9Wy5YNwQMsQ6PLLki+rKfoDOVc8QzkMZobJ92Xklcw/7keXZWW6Yk/mbrNHLfaUAqICgGFrBxtzwPipDRpoEDvZFaAe1OTqSCCF6rr3ok/uGkjETJag=
